"""
    hermes

    Messages sender service  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import hermes_client
from hermes_client.model.client_cert import ClientCert


class TestClientCert(unittest.TestCase):
    """ClientCert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientCert(self):
        """Test ClientCert"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClientCert()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
