"""
    hermes

    Messages sender service  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import hermes_client
from hermes_client.api.topics_publish_subscribe_api import TopicsPublishSubscribeApi  # noqa: E501


class TestTopicsPublishSubscribeApi(unittest.TestCase):
    """TopicsPublishSubscribeApi unit test stubs"""

    def setUp(self):
        self.api = TopicsPublishSubscribeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_api_v1_pubsub_demo_get(self):
        """Test case for get_api_v1_pubsub_demo_get

        Get  # noqa: E501
        """
        pass

    def test_publish_message_api_v1_pubsub_post(self):
        """Test case for publish_message_api_v1_pubsub_post

        Publish Message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
