"""
    hermes

    Messages sender service  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import hermes_client
from hermes_client.model.error_data import ErrorData


class TestErrorData(unittest.TestCase):
    """ErrorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorData(self):
        """Test ErrorData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
