"""
    hermes

    Messages sender service  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import hermes_client
from hermes_client.model.bearer_token import BearerToken


class TestBearerToken(unittest.TestCase):
    """BearerToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBearerToken(self):
        """Test BearerToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BearerToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
