"""
    hermes

    Messages sender service  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import hermes_client
from hermes_client.api.sms_send_api import SMSSendApi  # noqa: E501


class TestSMSSendApi(unittest.TestCase):
    """SMSSendApi unit test stubs"""

    def setUp(self):
        self.api = SMSSendApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sms_api_v1_sms_post(self):
        """Test case for sms_api_v1_sms_post

        Sms  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
