"""
    hermes

    Messages sender service  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import hermes_client
from hermes_client.model.basic_auth import BasicAuth


class TestBasicAuth(unittest.TestCase):
    """BasicAuth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBasicAuth(self):
        """Test BasicAuth"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BasicAuth()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
