"""
    hermes

    Messages sender service  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import hermes_client
from hermes_client.model.publish_payload import PublishPayload


class TestPublishPayload(unittest.TestCase):
    """PublishPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublishPayload(self):
        """Test PublishPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PublishPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
