"""
    hermes

    Messages sender service  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import hermes_client
from hermes_client.model.api_key import ApiKey


class TestApiKey(unittest.TestCase):
    """ApiKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiKey(self):
        """Test ApiKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
